### ISSUE TITLE
Error: Could not detect language for functions at monorepo/apps/api/isolate

### ISSUE THREAD

**Issue by gabyshev** [0x80/isolate-package#33] opened 2023-11-28 09:48 UTC
Hello,
I'm trying to setup isolate in my monorepo setup. (turbo + pnpm)

I have root level firebase.json
```
....
  "functions": [
    {
      "predeploy": ["turbo build --filter api", "isolate"],
      "source": "apps/api/isolate",
      "codebase": "api",
      "runtime": "nodejs18"
    }
  ]
}
```

And `isolate.config.json`:
```
{
  "targetPackagePath": "apps/api",
}
```

That `apps/api` have only 1 dependency `packages/mypackage` and in package.json I'm using `"mypackage": "workspace:*"`.

I checked Prerequisites in the README and made sure that all good.

However when I try to deploy functions from root I got this error:

```
firebase deploy -P firebase-project --only functions:api:myFunc
...
✔  functions: Finished running predeploy script.
i  functions: preparing codebase api for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled

Error: Could not detect language for functions at /path_to_monorepo/apps/api/isolate
```

And in `apps/api/isolate`
I see: `__tmp/mypackage-0.0.0.tgz`

I wonder what I have missed?

**Comment by gabyshev** [comment] 2023-11-28 10:14
Tried to move firebase.json to target app folder.

This time the error is different:

```
Error: Command failed: pnpm pack --pack-destination /path_to_monorepo/apps/api/isolate/__tmp

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12)

Error: functions predeploy error: Command terminated with non-zero exit code 1
```

Node version 18.16.0

**Comment by 0x80** [comment] 2023-11-28 11:19
I have seen this error when Firebase looks at the wrong directory and can not find your source code.

Try running with { logLevel: "debug" } in your isolate config to get more insights and then try to update your "source" field in firebase.json

**Comment by 0x80** [comment] 2023-12-17 21:10
Closing this issue assuming the problem is not with this library. Feel free to open it again if you have more info.

**Closed by 0x80** 2023-12-17 21:10 UTC
